server:
  port: 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/freshbazaar
    username: freshbazaar_user
    password: fb8EHjuZU56aerFpPiDbpssWrd
  jpa:
    properties:
      hibernate:
        default_schema: identity_service
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    schemas: identity_service
    create-schema: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2
  expiration: 3600000