server:
  port: 8081

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/freshbazaar
    username: freshbazaar_user
    password: fb8EHjuZU56aerFpPiDbpssWrd

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: identity_service
    default-schema: identity_service
    baseline-on-migrate: true


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: identity_service
    show-sql: true
    open-in-view: false

jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2
  expiration: 3600000

logging:
  level:
    org.flywaydb: INFO