server:
  port: 8081

spring:
  application:
    name: idenity-service-api

  datasource:
    url: jdbc:postgresql://localhost:5432/freshbazaar?currentSchema=identity_service_api
    username: freshbazaar_user
    password: fb8EHjuZU56aerFpPiDbpssWrd

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: identity_service_api
    default-schema: identity_service_api

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true